### ISSUE TITLE
Make release 1.0

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/rail#17]
This will require the follow issues to be closed

- [x] LSSTDESC/RAIL#41
- [x] LSSTDESC/RAIL#47
- [ ] LSSTDESC/rail_base#5
- [x] LSSTDESC/RAIL#182
- [ ] LSSTDESC/rail_base#6
- [x] LSSTDESC/RAIL#238
- [ ] LSSTDESC/rail_base#7
- [x] LSSTDESC/rail_astro_tools#3
- [x] LSSTDESC/RAIL#244 
- [x] LSSTDESC/RAIL#245 
- [ ] LSSTDESC/rail_hub#22 
- [x] LSSTDESC/RAIL#264 
- [ ] LSSTDESC/rail_bpz#30
- [ ] LSSTDESC/rail_bpz#29
- [x] LSSTDESC/RAIL#319 
- [x] LSSTDESC/RAIL#320

**Comment by aimalz** [comment]
LSSTDESC/RAIL#47, LSSTDESC/rail_base#5, LSSTDESC/RAIL#182, and LSSTDESC/rail_base#6 may also be considered essential for v1, but I vaguely recall that they were already at least partially addressed in other PRs so can perhaps be closed without further action?

**Comment by eacharles** [comment]
overtaken by events

**Comment by aimalz** [comment]
This has been superseded by [this issue-tracking GH Project](https://github.com/orgs/LSSTDESC/projects/9).
