### ISSUE TITLE
Implement changes to rail eco system and package dependence.

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/rail#19]
This is the big issue for describing the steps to implement the changes to the rail ecosystem.

- [x] LSSTDESC/RAIL#374 
- [x] LSSTDESC/RAIL#375
- [x] LSSTDESC/RAIL#376
- [x] LSSTDESC/RAIL#377
- [x] LSSTDESC/RAIL#378
- [x] LSSTDESC/rail_hub#14
- [x] LSSTDESC/rail_hub#24
- [x] LSSTDESC/RAIL#394
- [x] LSSTDESC/rail_hub#36

Once we finalize package names we can connect the doc built rail_hub to readthedocs in a sensible fashion.

**Comment by eacharles** [comment]
Done
